### ISSUE TITLE
標點符號輸入窗無法切換

### ISSUE THREAD

**Issue by seventhsky** [ettoolong/BBSFox-E10S#16]
在切換符號時，只能切到"線框"這欄，而且會切不回去。

**Comment by ettoolong** [comment]
嵌入影片視窗的下拉選單也有一樣的問題, 但關掉 E10S 後可以正常.
所以推測是 FX 本體的 bug, 即 content page 中XUL物件的事間觸發不正常,
目前暫時把下拉選單用 html 的 select tag 改寫.
