### ISSUE TITLE
設定視窗多出橫向及縱向卷軸

### ISSUE THREAD

**Issue by pupu2314** [ettoolong/BBSFox-E10S#22]
作業系統：Windows 10 x64
Firefox版本：42.0a1 (2015-08-01) x64
BBSFox 版本：4.0.13

若需要其他套件清單或資訊再麻煩作者告知，謝謝。

![image 1](https://cloud.githubusercontent.com/assets/936456/9024502/5c72f444-3905-11e5-9b3e-62b8f81fce68.png)

**Comment by ettoolong** [comment]
已修正, 謝謝.
