### ISSUE TITLE
顯示部份日文或符號時變亂碼

### ISSUE THREAD

**Issue by LVane** [ettoolong/BBSFox-E10S#23]
作業系統: Windows 10 x86

目前在Stable(41)及Beta版(42)均可以正常顯示
![beta](https://cloud.githubusercontent.com/assets/14927481/10235562/0f6cb716-68d0-11e5-97c7-ab449857561d.jpg)

但是到Dev(43)及Nightly(44)版後就顯示不正確
![dev](https://cloud.githubusercontent.com/assets/14927481/10235586/38c571d4-68d0-11e5-92f4-993bc0348420.jpg)

**Comment by seventhsky** [comment]
同樣的問題
Windows 10 x64 Firefox 43.0b1

**Comment by ettoolong** [comment]
相關 bug 討論:
https://bugzilla.mozilla.org/show_bug.cgi?id=912470
https://bugzilla.mozilla.org/show_bug.cgi?id=1222876

簡單來說就是, FX43後移除了 '台灣big5' to 'unicode' 的對應.
BBSFox 之後會內建自己的UAO對應, 以修正這個問題.
