### ISSUE TITLE
推文看不見游標

### ISSUE THREAD

**Issue by seventhsky** [ettoolong/BBSFox-E10S#24]
推文的時候常常會看不見游標，要修改文字時很不方便
![1](https://cloud.githubusercontent.com/assets/12661302/11167056/e97f6eec-8b8c-11e5-99c6-d0c180dee6cd.png)
還有發文的標題
![3](https://cloud.githubusercontent.com/assets/12661302/11167057/f5454954-8b8c-11e5-8bf3-a0ab984bfa04.png)
但內容編輯畫面很正常
![4](https://cloud.githubusercontent.com/assets/12661302/11167058/0133b11a-8b8d-11e5-916f-17eabd21784d.png)

**Comment by ettoolong** [comment]
在 4.0.18 版作了些調整, 請幫忙測看看. 謝謝.

**Comment by seventhsky** [comment]
推文跟發文的標題都看的見游標了 謝謝^_^
