### ISSUE TITLE
字型問題

### ISSUE THREAD

**Issue by rovalerui** [ettoolong/BBSFox-E10S#25]
在Mac上一直有字型的問題
而且最近幾次Firefox改版又讓字體高度和垂直對齊變得很怪
是否可以像這一樣：https://forum.moztw.org/viewtopic.php?t=32493
使用瀏覽器本身的字型設定
半形字用 font.name.monospace.*
全形字在 font.name.monospace.\* 設定的字型未包含中文字符時 fallback到其他預設字型

或者讓英文字型和中文字型可分開設定
因為中文沒有等不等寬的問題
拆開來可以讓字型的選擇更靈活

**Comment by ettoolong** [comment]
首先 FireSSH 修改版和 BBSFox 在顯示這部份有很大的差異.
該修改版使用的是 **繪圖模式** , 而 BBSFox 使用的是 **文字模式** ,
繪圖模式有個好處就是可以直接叫瀏覽器 "畫" 一個字, 並且畫成  "指定的寬度".
所以就算你選的字不是等寬字, 畫的時候, 瘦的字就會被拉寬.
至於文字模式, 在處理各種字的問題, 就需要靠標準的 HTML tag 和 CSS.
如果 HTML 和 CSS 有某些限制, 有些效果就是會作不出來.

再來, BBSFox 不太可能採用瀏覽器本身的字型設定,
因為那個設定介面比你設定中英文字型 **複雜**太多. 因此不考慮.
但是如果你知道怎麼調. 你可以直接把它 "優先使用網頁指定字型" 勾選拿掉.
然後調看看能不能調出你要的效果. 如果你在那上面都調不出來.
那我更無可能按照它的 fallback 規則作出一樣的效果來.
因為只要拿掉那個勾選, BBSFox 的頁面上的字就會照 Firefox 內的規則顯示.
如果你試出好的結果, 也可分享看看.

至於中英文分開設定. 目前知道有兩個作法:
方法1:
我改 code,
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range
照上面講的作, 但是很不幸, 目前測試後, 看來也就它上面的例子可以,
如果你在它的範例裡加入中文字, 結果就會錯誤(跟 Chrome 對比),
證明 Firefox 在 CSS unicode-range 這部份依然有 bug.

方法2:
我改 code, 在目前輸出文字的地方針對中文設字型. 這可能會讓畫面輸出變慢. 可能不是一個好解法.
另一個修改較小, 改某個 CSS, 但我不確定會不會有其它副作用. 改了可能要讓很多人測,
才能保證沒造成其他問題.

方法3:
用 BBSFox 目前的功能, 參考下面這個說明: 
https://github.com/ettoolong/BBSFox-E10S/wiki/Q&A#%E4%BD%BF%E7%94%A8%E6%80%9D%E6%BA%90%E9%BB%91%E9%AB%94%E6%88%96%E5%85%B6%E4%BB%96%E7%AD%89%E5%AF%AC%E5%AD%97%E9%AB%94%E4%BD%86%E5%8D%BB%E9%81%87%E5%88%B0%E8%A1%8C%E9%AB%98%E5%95%8F%E9%A1%8C%E8%83%8C%E6%99%AF%E8%89%B2%E8%93%8B%E5%88%B0%E5%88%A5%E8%A1%8C
這方法在 google noto sans mono 下也可行.

方法4:
找適合的字型, 抓一個別人作好的字型, 這字型不可以有寬度和高度問題. 然後裝到你的 Mac 裡:
例如下面這個:
https://github.com/iamchucky/PttChrome/raw/gh-pages/fonts/symmingliu.woff
如果你不想抓下來, 也可以線上使用, 方法如下:
裝 stylish, https://addons.mozilla.org/zh-tw/firefox/addon/stylish/
幫 PTT 設定一個樣式, 大概長這樣:
`@namespace url(http://www.w3.org/1999/xhtml);`

`@-moz-document url("telnet://ptt.cc/") {`
`@font-face {`
`font-family: SymMingLiu;`
`src: url('https://github.com/iamchucky/PttChrome/raw/gh-pages/fonts/symmingliu.woff');`
`}`
`@font-face {`
`font-family: DFHeiLightB5;`
`src: url('https://github.com/iamchucky/PttChrome/raw/gh-pages/fonts/DFHeiLightB5.woff');`
`}`
`}`
然後去 BBSFox 的設定頁, 把字型設成 SymMingLiu (不會在下拉選單內, 要自己輸入).
這樣就會套用這個字型. 如果你是直接把字型抓下來裝了, 那就直接在下拉選單中選,
不用裝 stylish.
效果大概是這樣:
![2016-01-27 19 35 34](https://cloud.githubusercontent.com/assets/909570/12612396/4f0fc340-c52d-11e5-8dd6-882913823a59.png)
如果你是線上使用, 沒有安裝到你電腦裡, 那每次開PTT站台, 可能會有一小段時間畫面歪掉,
因為瀏覽器還在抓字型.

方法5:
找適合的字型, 找一台 windows 電腦, 把它的細明體 copy 出來裝到 Mac, 看起來大概像這樣:
![2016-01-20 09 36 38](https://cloud.githubusercontent.com/assets/909570/12612149/ac44528a-c52b-11e5-8893-a60243b935c6.png)
![2016-01-20 09 37 29](https://cloud.githubusercontent.com/assets/909570/12612153/b28f6b7a-c52b-11e5-9628-edabede08db6.png)

**Comment by ettoolong** [comment]
對了, 可如果可以, 也請提供你那邊出問題的截圖和字型名稱. 方便測試. 謝謝.
我在這幾版 Mac 和 Firefox 升級當中, 並沒有遇到字體高度和垂直對齊的問題.
有問題的字不管在哪版 Firefox 都還是有問題, 沒問題的字體一直都是正常的.

**Comment by rovalerui** [comment]
我是用思源黑體遇到行高和對齊問題 不過看來用方法3可以解決

**Comment by ettoolong** [comment]
結案
