### ISSUE TITLE
點擊 Twitch 的連結會造成 flash 載入多次

### ISSUE THREAD

**Issue by legnaleurc** [ettoolong/BBSFox-E10S#26]
Iceweasel 44.0.2 (GNU/Linux x64)
BBSFox 4.0.18.1

問題出在 https://player.twitch.tv/js/player.js
其中一行

``` javascript
e.postMessage(r, '*');
```

那個 e 是以

```
window.opener || window.parent
```

拿到的

猜測是為了和第三方服務整合
從一般網頁點過去並不會有問題

但是若是從 BBSFox 點過去則會因為它是 chrome window 而丟出 permission denied
導致 Twitch 回收舊的 flash player 失敗 (大概為了 robustness, Twitch 採用的是延遲太久就砍掉 flash player 再開新 player 的方案)
頁面上 flash player 太多就卡死了

**Comment by ettoolong** [comment]
在 BBSFox 中用滑鼠左鍵點連結 -> 有 opener
在 BBSFox 中用滑鼠中鍵點連結 -> opener = null
在 BBSFox 中的快顯功能表中連結另開分頁 -> opener = null

暫時還沒想到比較好的解法, 在修好前, 有遇到這問題的人可以先用:
滑鼠中鍵點開 twitch 連結 或 快顯功能表中用連結另開分頁.

目前已知的幾個修法都不是很好, 只能暫時解決.
等我想到比較好的修正方式再更新.
謝謝回報.

**Comment by legnaleurc** [comment]
https://bugzil.la/1256249

I guess Gecko 48 has fixed this somehow, I don't know why lol.

**Comment by ettoolong** [comment]
目前版本中的 workaround:
https://github.com/ettoolong/BBSFox-E10S/commit/eda9e3595ff9980ace23899ab44c6e55ff0c909b

雖然 FX48 修正了, 不過因為 FX45 仍然是 BBSFox 5.X 中最低的支援版本,
且 FX45 也是目前最新的 ESR 版,
所以 workaround 的 code 暫時不會移除, 直到下一個 ESR 版本後才會上修最低支援版本到 FX48.
