### ISSUE TITLE
拜託支援firefox44.0

### ISSUE THREAD

**Issue by cockatiel123** [ettoolong/BBSFox-E10S#27]
我是使用fx 32位元版本
他寫不支援，可是我很需要使用啊!!
拜託了!!!
謝謝

**Comment by ettoolong** [comment]
因為 Firefox 41~44 這幾版有一個 TSF 的 bug, 這會影響到 BBSFox 內的中文輸入,
所以除非你有特殊原因, 不然建議你還是升到 Firefox 45,

如果你因為特殊原因非用 Firefox 44 不可, 可以裝下面這邊的這個 release 中的 xpi 檔:
https://github.com/ettoolong/BBSFox-E10S/releases/tag/v4.0.23

安裝這個版本, 需注意:
1. 因為這不在 AMO 上, 所以沒簽章, 但是這和 AMO 上的版本應該是一樣的, 除了 FX 版本限制以外.
若因為沒有簽章而無法裝, 請到 about:config 下把 xpinstall.signatures.required 的值改成 false.
1. 如果你是在 windows 平台上使用, 你應該可能會遇到 上面提到的 TSF bug,
   請到 about:config 下把 intl.tsf.enable 改成 false.
