### ISSUE TITLE
關於 UAO 的 license

### ISSUE THREAD

**Issue by eight04** [ettoolong/BBSFox-E10S#28]
ettoolong 大你好，我在一個檢視 ANSI 檔的 Addon 中使用了您的 uao.js 和 b2u.tab（https://github.com/eight04/ansi-viewer/tree/master/main/uao ）。我想確認一下 License 的問題︰
1. b2u.tab 也是以 GPL 發行的嗎？
2. uao.js 也是以 GPL 發行的嗎？若是，那我使用這份檔案是否表示該 Addon 也必需要用 GPL 發行？
3. 若 2 為是，未來會有計劃釋出較寛鬆的 library 版本嗎？

**Comment by ettoolong** [comment]
逐一回答你:
1. 如果你直接取用這個專案裡提供的，是 GPL 授權
2. 同上
3. 因為這專案早期的 code 來自 PCMAN 在 2009 年釋出的 pcmanfx (以GPLv2 釋出)，
除非取得 PCMAN 本人同意，否則未來不會以較寛鬆的授權釋出。

在一年前曾有些開發者致信過 PCMAN，希望以 MIT 授權，不過未獲正面回應，
事實上我也希望能改成 MIT 授權的，這問題我建議你直接寫信給 PCMAN 本人。

至於 UAO 部份其實是有其它來源的，我建議你參考：
https://github.com/pcman-bbs/pcman-firefox/blob/master/license.txt

**Comment by eight04** [comment]
瞭解了，感謝回覆。那麼我先把這個 issue 移到 https://github.com/pcman-bbs/pcman-firefox
