### ISSUE TITLE
黑名單問題

### ISSUE THREAD

**Issue by kamoniki** [ettoolong/BBSFox-E10S#30]
firefox 46.0.1

bbsfox 4.0.25
新增站台(PTT)，後面雜項開啟黑名單，輸入 ID，重開，仍然沒有變化，該推文仍然是亮的。

**Comment by ettoolong** [comment]
無法重現

**Comment by ettoolong** [comment]
這還有再測嗎? 我這邊測都已經正常。
如果還有發生再另外開 issue.

**Comment by kamoniki** [comment]
感謝您，目前正常沒問題，不過我是有關掉E10S

2017年3月13日 11:16，"ettoolong" <notifications@github.com>寫道：
