### ISSUE TITLE
滑鼠左/右鍵+滾輪無作用

### ISSUE THREAD

**Issue by polar2031** [ettoolong/BBSFox-E10S#31]
會變成正常滾動滾輪
停用過FireGesture但情況不變
另外若設定FireGesture的滾輪手勢為切換分頁
使用該手勢切換至BBSFox作用的頁面時
該頁面會受到最後的滾輪動作影響
(e.g. 右鍵+滾輪up切換至該頁面時會出現BBSFox裡滾輪up的行為)

版本: Firefox 48.0b3

**Comment by ettoolong** [comment]
在 5.0.2 版中修正, 請幫忙抓新版本測看看, 謝謝.

**Comment by polar2031** [comment]
5.02 修正後出現的問題
若使用FireGesture的滾輪手勢(右鍵+滾輪)切換分頁
離開BBSFox頁面後
再以其他方式(滑鼠點擊 or Ctrl+tab)切換回該頁面
會出現滑鼠滾輪失效的情形
於該頁面點擊右鍵
或是再次以滾輪手勢切換回該分頁即回復正常

反之若是使用點擊或快速鍵切換分頁離開BBSFox分頁
再以滾輪手勢切換回來時右鍵按住的動作會被吃掉
舉例來說
我先點擊BBSFox 右邊分頁
接著想用滾輪手勢切換至BBSFox 的左邊分頁
動作是右鍵按住+滾輪往上滾兩格
滾輪滾第一格切換至BBSFox 頁面的動作是成功的
但是滾輪滾第二格時不會繼續切換分頁
而是變成BBSFox 頁面滾輪的動作
(右鍵放開後重試就能正常動作)

BBSFox 版本: 5.03版
Firefox 版本: 49.02a2
(Beta版本目前無視 about:config 設定，強制要求套件的 signature)

**Comment by ettoolong** [comment]
更新了 5.0.4 版, 修正上面提到的滾輪切分頁問題,
請幫忙抓新版本再測看看, 謝謝.

**Comment by ettoolong** [comment]
這問題應該是修正了, 先關掉 issue, 若還有問題再重開.
