### ISSUE TITLE
ctrl+b 指令自動轉為 ctrl+t

### ISSUE THREAD

**Issue by holishing** [ettoolong/BBSFox-E10S#32]
自最近一次更新後出現此問題

相關回報文章如下：
https://www.ptt.cc/bbs/PttBug/M.1473595208.A.E92.html

**Comment by ettoolong** [comment]
已確認是改版造成的 bug. 會儘快修正. 謝謝回報.

**Comment by ettoolong** [comment]
已修, 若還有問題再回報.
