### ISSUE TITLE
可以設定鍵結開啟在背景分頁嗎?

### ISSUE THREAD

**Issue by fun178** [ettoolong/BBSFox-E10S#33]
有開啟"偵測鍵結"功能，點擊後開啟在前景分頁，可以設定成開啟在背景分頁嗎?

**Comment by ettoolong** [comment]
請參考:
[點了BBS中的鏈結可以不要跳到新分頁嗎](https://github.com/ettoolong/BBSFox-E10S/wiki/Q&A#%E9%BB%9E%E4%BA%86bbs%E4%B8%AD%E7%9A%84%E9%8F%88%E7%B5%90%E5%8F%AF%E4%BB%A5%E4%B8%8D%E8%A6%81%E8%B7%B3%E5%88%B0%E6%96%B0%E5%88%86%E9%A0%81%E5%97%8E)

**Comment by fun178** [comment]
感謝，已解決，過程如下

1.原本就有裝TMP且**設定>分頁>開啟分頁>彈出視窗**是無勾選狀態
2.裝5.0.14 版->無效
3.BBSFox設定中勾選**BBS畫面點擊鏈結後不要自動跳到新的分頁**->有效

使用環境: Firefox 49 + BBSFox 5.0.14
