### ISSUE TITLE
"ctrl+滑鼠左鍵開連結於新頁" 與 "瀏覽圖片模式"

### ISSUE THREAD

**Issue by nNullSpace** [ettoolong/BBSFox-E10S#34]
使用環境: Firefox 48.0.2 + BBSFox 5.0.13
1. 瀏覽bbs時, ctrl + 滑鼠左鍵, 之前都可以開連結於背景頁籤, 而不會跳過去,
   現在則是開連結於新頁並且直接跳過去瀏覽,
   這跟 "只有按滑鼠左鍵" 的行為重複了, 瀏覽上也較為不方便.
   因為有的使用者會想先用配合ctrl的滑鼠左鍵先打開所有連結後再去觀看,
   建議將 "ctrl + 滑鼠左鍵" 設定為開連結於背景頁面, 或者讓使用者自訂
2. 建議新增瀏覽圖片模式
   比方頁面內有很多連結指向 imgur.com 之類圖庫網站時, 可以透過 右鍵選單某項 或是 熱鍵
   切換到特別瀏覽模式, 可以按方向鍵或PgUp/Down鍵來看圖
   也可以切到縮圖式列表, 然後按esc時退出回到一般讀取文章功能

**Comment by ettoolong** [comment]
1. 應該是可以修正的, 下一版會試著修.
2. 建議你直接用 [開啟文章網址](https://github.com/ettoolong/BBSFox-E10S/wiki/PTT-Function#%E9%96%8B%E5%95%9F%E6%96%87%E7%AB%A0%E7%B6%B2%E5%9D%80) 這功能替代.

**Comment by ettoolong** [comment]
請幫忙測試 5.0.14 版, 修正問題1

**Comment by nNullSpace** [comment]
開發者您好, 感謝您迅速的回應

不過那個....我在 FireFox 中看不到更新呢, 還是有什麼其他方式可以進行測試?
![1](https://cloud.githubusercontent.com/assets/22057021/18607327/69b412dc-7cfc-11e6-8ad2-7e07ad3c9571.png)

**Comment by ettoolong** [comment]
測試版在這邊  https://github.com/ettoolong/BBSFox-E10S/releases
然後你可能會因為簽章問題而無法直接安裝, 因為 AMO 上的才有簽章,
你可以先參考 [這邊](https://github.com/ettoolong/BBSFox-E10S/wiki/Q&A#%E5%AE%89%E8%A3%9D%E6%B8%AC%E8%A9%A6%E7%89%88%E6%99%82%E5%9B%A0%E5%A5%97%E4%BB%B6%E6%9C%AA%E7%B0%BD%E7%AB%A0%E8%80%8C%E7%84%A1%E6%B3%95%E5%AE%89%E8%A3%9D) 測完後記得改回來, 讓 Firefox 的簽章驗證重新生效.

**Comment by nNullSpace** [comment]
謝謝, 不過我這幾天外出, 暫時沒辦法做這測試, 我等正式釋出再用好了0.0

**Comment by ettoolong** [comment]
測試完才會上AMO, 推有問題的版本上去是浪費審查的人力.

**Comment by ettoolong** [comment]
真的沒人要測, 關了.
