### ISSUE TITLE
不定時自動斷線

### ISSUE THREAD

**Issue by EuanJones** [ettoolong/BBSFox-E10S#35]
OS: Windows10 64bit
ISP: 中華電信
Fx: 49.0.1

使用此套件瀏覽ptt時，如果一段時間沒有使用（時間不固定，短則數分鐘，長則數小時），則會自動斷線，必須重新整理該頁面才能繼續使用。已經嘗試過重新安裝Fx、重新安裝此套件、除了此套件其餘套件全部停用...等等除錯方式都無法解決。

但奇怪的是，在OSX中使用Fx+BBSFox卻不會有斷線問題，讓人有些困擾。不知是否能找到問題並修正呢？

**Comment by ettoolong** [comment]
先參考 [斷線問題](https://github.com/ettoolong/BBSFox-E10S/wiki/ConnectToHost#%E6%96%B7%E7%B7%9A%E5%95%8F%E9%A1%8C) 這篇的設定試看看

**Comment by EuanJones** [comment]
完全有效！謝謝
