### ISSUE TITLE
和 Beyond Australis 衝突導致畫面右邊被切掉

### ISSUE THREAD

**Issue by wum0u** [ettoolong/BBSFox-E10S#36]
![sp161010_205348](https://cloud.githubusercontent.com/assets/16879992/19236774/b80f4154-8f2b-11e6-98c3-5763e4aea24e.png)
如果用 Beyond Australis 隱藏工具列，同時BBSFox設定隨視窗大小調整字體的話，最右邊會被切掉。
我使用細明體，應該不是非等寬字體的問題。

**Comment by ettoolong** [comment]
先參考這篇 [畫面最右邊有些字被切掉了](https://github.com/ettoolong/BBSFox-E10S/wiki/Q&A#%E7%95%AB%E9%9D%A2%E6%9C%80%E5%8F%B3%E9%82%8A%E6%9C%89%E4%BA%9B%E5%AD%97%E8%A2%AB%E5%88%87%E6%8E%89%E4%BA%86) 看看是不是縮放問題，我裝 Beyond Australis 測試後是滿正常的。

**Comment by wum0u** [comment]
試過了，不是，但是放大到120%就變正常了。

**Comment by ettoolong** [comment]
調到 100% 以外的縮放只會讓你後續遇到更多問題，建議還是查出問題真正的原因。
幾個方向可以測試：
1. 你再出問題時把 Beyond Australis 停用，畫面就正常了嗎？
2. 是否有套用一些自訂的頁面樣式？

**Comment by wum0u** [comment]
我把全部套件停用，只開啟 BBSFox 和 Beyond Australis 後問題一樣存在，再關閉 BA 就正常了。

**Comment by ettoolong** [comment]
真糟糕 Orz
因為我這邊是無法重現，這樣會無法查問題。
我已經在 Mac 和 Win10 上測過，FX 測過 49 和 51 版，都是正常。

如果可以的話，先用 portable 版的 FX 測看看？
http://portableapps.com/apps/internet/firefox_portable
它是綠色安裝，測完直接把資料夾砍了就可以。
如果 portable 沒問題，那表示你原本的 Firefox 可能還有某種設定造成問題。

再來就是查問題的部份：
1. 先到 **BBSFox 的設定頁 > 快顯功能表 > Firefox 快顯功能表 > 在 BBS 視窗隱藏快顯功能表[檢測元素]項目** 取消勾選。
1. 開一頁 BBS，在上面按滑鼠右鍵，選檢測元素。
   這時視窗下方會有一個工具窗，為了避免工具窗占用視窗高度影響測試結果，先按一下工具窗的 [顯示於不同視窗] 這個鈕(在工具窗的右上角，關閉鈕的左邊)，把工具視窗彈出成獨立的窗。
2. 在網頁元素的樹狀圖中找 **BBSWindow**
   ![bbswindow](https://cloud.githubusercontent.com/assets/909570/19273839/9eb94648-9000-11e6-82f2-6dfc45b62e1f.png)
   和 **main**
   ![main](https://cloud.githubusercontent.com/assets/909570/19273848/a8186e3a-9000-11e6-800d-25ae345c8ea7.png)
   這兩個節點

然後我需要這些資訊：
1. BBSWindow 節點的 style 的 height 和 width 的值
2. main 節點的 style 的值

先確認這時你頁面的縮放是100%
然後調一下 Firefox 的視窗大小觀察被切字的現像是否產生，當切字問題發生時，
記下上面的值，如果可以不用把視窗拉到很大，就能重現的話，
那請提供我在較小視窗上重現的值，因為我家螢幕可能沒你的大。

謝謝測試。

**Comment by wum0u** [comment]
```
<div id="BBSWindow" style="height: 640px; width: 985px; cursor: auto;" align="center">
```

```
<div id="main" class="main" style="font-size: 24px; line-height: 24px; overflow: hidden; text-align: left; width: 960px; margin-top: 32px; transform: none; transform-origin: center center 0px; border: 0px none; font-family: MingLiU,Osaka-Mono,monospace;">
```

這樣可以嗎？

我在猜應該跟以下有關
1. 我有使用 Mactype，所以把硬體加速關了；再開啟就恢復正常。
2. 我習慣把 Windows 工作列擺在左邊，移回下面的話在最大化下顯示正常，但其他大小還是會切字。

**Comment by ettoolong** [comment]
好的，我想我可以先測測 MacType 的影響。
所以你那邊的設定是：
裝了 MacType + 關了 Firefox 的硬體加速這樣？
作業系統是 Win10 還是 Win7？

然後硬體加速是在下圖這邊關的嗎？還是有從其它地方關過？
![ha](https://cloud.githubusercontent.com/assets/909570/19314156/b824bd76-90cb-11e6-8596-8656325e43bc.png)

如果有調整過其它的渲染設定(例如 about:config 裡的其它設定)可以一起提供一下，我一併測看看。
謝謝。

**Comment by wum0u** [comment]
我是用 MacType 1.2016.904.0，Firefox 關閉硬體加速（從設定關的，沒碰過 Firefox 的渲染設定），作業系統是Window 10（已更新到最新版）。

**Comment by ettoolong** [comment]
報歉，回很慢，因為我花了好幾天研究和修正這個問題。
現在有一個測試版，要麻煩你幫忙測測。

先到 [這邊](https://github.com/ettoolong/BBSFox-Beta/releases) 抓 5.0.15 版。
你可能會遇到簽章問題而無法裝，再參考 [這篇](https://github.com/ettoolong/BBSFox-E10S/wiki/Q&A#%E5%AE%89%E8%A3%9D%E6%B8%AC%E8%A9%A6%E7%89%88%E6%99%82%E5%9B%A0%E5%A5%97%E4%BB%B6%E6%9C%AA%E7%B0%BD%E7%AB%A0%E8%80%8C%E7%84%A1%E6%B3%95%E5%AE%89%E8%A3%9D) 把測試版裝起來。

裝好後，於網址列輸入 **about:config** 搜尋 **extensions.bbsfox2.DynamicRenderTest** 改成 **true**。

然後連 BBS 測試是否修正問題。謝謝測試。

**Comment by wum0u** [comment]
修正了，謝謝！
不過在沒有最大化的視窗下，旁邊的留空有點大，是故意的嗎？

**Comment by ettoolong** [comment]
每當你調整視窗大小，BBSFox 就會重新計算要用多大的字來顯示。

規則是：
**選用的字體大小乘80個英文字寬不可以超出你視窗的寬度** 且 **選用的字體大小乘24個英文字高不可以超出你視窗的高度**

在這個規則之下會得到一個最大的可用字體大小，
上下或左右的留黑就是你的 **視窗寬高** 減去最後算出的 **字體大小顯示24*80**，也就是餘數。
亦即：在此視窗大小下，字體增大一個px，就會超出寬或高。

不知道這樣解釋有沒有清楚。

**Comment by wum0u** [comment]
原來如此，瞭解了。謝謝你這麼用心回答我的問題XD
