### ISSUE TITLE
Developer Edition 連 ptt.cc黑畫面

### ISSUE THREAD

**Issue by yjlintw** [ettoolong/BBSFox-E10S#37]
Firefox Developer Edition
Version: 52.0a2(2016-11-30)(64-bit)
OS: macOS 10.12

連線至telnet://ptt.cc or ssh://bbs@ptt.cc呈現黑畫面
stable版本的firefox則正常

**Comment by ettoolong** [comment]
已測試. 真的壞了, Mac 版不行, Win10 52.0a2(2016-11-30)(64-bit) 則正常.
我要查一下原因.
謝謝回報.

**Comment by ettoolong** [comment]
更新一下目前處理的進度：

已知的部份，因為新版本 FX 的 sandbox 有些改動，將無法在 content process 開 socket，所以造成了這個問題。至於在 Mac 上無法連線，而在 Windows 上正常，是因為 sandbox 的改動在 Mac 版本已經先實作好了，之後 Mac 以外的平台應該也會陸續套用，所以這問題勢必要在 BBSFox 上修正。

在 about:config 中把 security.sandbox.content.level 改成 0 可以讓連線正常(改了後須重開FX)，但不建議你改，因為這跟安全性有關。

BBSFox 部份我已經在修了，改的部份有點多，預計還需要幾天時間，改好後我一樣會在這邊通知，到時候可能要麻煩你幫忙測測。謝謝。

**Comment by ettoolong** [comment]
現在有一個測試版，要麻煩你幫忙測測。

先到 [這邊](https://github.com/ettoolong/BBSFox-Beta/releases) 抓 5.0.17 版。
你可能會遇到簽章問題而無法裝，再參考 [這篇](https://github.com/ettoolong/BBSFox-E10S/wiki/Q&A#%E5%AE%89%E8%A3%9D%E6%B8%AC%E8%A9%A6%E7%89%88%E6%99%82%E5%9B%A0%E5%A5%97%E4%BB%B6%E6%9C%AA%E7%B0%BD%E7%AB%A0%E8%80%8C%E7%84%A1%E6%B3%95%E5%AE%89%E8%A3%9D) 把測試版裝起來。

為了修正這個問題，改動很多地方，可能需要多測測其它功能是否正常。
謝謝測試。

**Comment by yjlintw** [comment]
初步使用正常,我盡量測試,但是firefox不是我主力工作的瀏覽器,所以可能測試效果有限

Edit: 而且我平常使用習慣只有閱讀跟偶而推文,所以有些地方可能會測試不到

**Comment by ettoolong** [comment]
已於 5.0.19 版修正
