### ISSUE TITLE
火狐更新後，無法驗證就被停用了

### ISSUE THREAD

**Issue by flameddd** [ettoolong/BBSFox-E10S#38]
Ett大大
火狐更新至「43.0.1」後，此元件就被視為「無法驗證BBSFox於Firefox使用，已被停用。」，此元件就被強制停用了。
火狐提出的相關連結為：https://support.mozilla.org/zh-TW/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

火狐上就你這套最好用！！

**Comment by ettoolong** [comment]
https://addons.mozilla.org/zh-TW/firefox/addon/bbsfox/versions/
看上面的版本相容性，FX 43.0.1 應該可以裝到 BBSFox 4.0.18 版吧。
不過因為 FX 41~45 這幾版有輸入法方面的問題，所以建議是能升到 45 以上。

**Comment by flameddd** [comment]
感謝ＥＴＴ大！！
我久久升級一次，沒想到火狐不是一次升到位
我馬上來試看看

測試ＯＫ了！　感謝ＥＴＴ大費心
