### ISSUE TITLE
ssh無法連線

### ISSUE THREAD

**Issue by kaoh08** [ettoolong/BBSFox-E10S#39]
ssh無法連線
測試版本 5.0.17

**Comment by ettoolong** [comment]
作業系統? Firefox 版本?
另外, 你有設定自動登入嗎? 還是直接在網址使用 ssh://bbs@ptt.cc 登入的?

**Comment by kaoh08** [comment]
改用ssh://bbs@ptt.cc後正常連線
上個正式版只用ssh://ptt.cc就可以連

Firefox 55 nightly, macOS 10.12.3
