### ISSUE TITLE
5.0.22版本於Nightly 56.0a1版本無法運作

### ISSUE THREAD

**Issue by pupu2314** [ettoolong/BBSFox-E10S#42]
5.0.22版本於Nightly 56.0a1版本

會持續轉圈且不會顯示任何訊息/內容

**Comment by ettoolong** [comment]
相容性問題, 新版送審中.

請見:
https://bugzilla.mozilla.org/show_bug.cgi?id=1362829
https://bugzilla.mozilla.org/show_bug.cgi?id=1319111

謝謝回報

**Comment by pupu2314** [comment]
感謝作者抽空答覆

也很高興問題已經修正

謝謝
