### ISSUE TITLE
油猴腳本不能在bbsfox下作用?

### ISSUE THREAD

**Issue by hdd60311** [ettoolong/BBSFox-E10S#44]
剛裝了個腳本結果發現在bbsfox下沒有作用
搜了下以前曾有人問過這問題但沒解答
https://www.ptt.cc/bbs/Browsers/M.1480376782.A.3AD.html

**Comment by ettoolong** [comment]
這應該是油猴本身就不支援 telnet 和 ssh 這兩個協定吧.

協定的支援我猜是在油猴的[這邊](https://github.com/greasemonkey/greasemonkey/blob/3f462ac1305712ce65b3e2b19c9c8c31f377cc8e/modules/util/isGreasemonkeyable.js)處理的

也許需要自己加上 telnet 和 ssh 這兩行:
```
function isGreasemonkeyable(url) {
 ...
    case "http":
    case "https":
    case "telnet":
    case "ssh":
    case "ftp":
      return true;
  ...
}
```

兩個方法:

1. 回報這個問題, 請油猴作者改 (我覺得有難度, 因為油猴作者可能根本不知道 BBSFox 是啥套件. 另外, BBSFox 和油猴也只能支援到 Firefox 56, 他們不見得願意再為了這個做修改)
2. 自己把油猴的套件抓下來修改後重新打包

**Comment by pupu2314** [comment]
請問作者BBSFox有支援 57的計劃嗎?

**Comment by ettoolong** [comment]
@pupu2314  目前沒有
