### ISSUE TITLE
第一次安裝時跳出的英文版說明頁有錯字

### ISSUE THREAD

**Issue by snyoung** [ettoolong/BBSFox-E10S#45]
第二張圖（閱讀文章的滑鼠手勢）底下的說明
http://imgur.com/a/i9eZt

反白處應該是Orange area

**Comment by ettoolong** [comment]
應該已經錯很久了, 都沒人發現. XDDD
下次更新一併修.

謝謝回報.

**Comment by ettoolong** [comment]
於 5.0.24 版修正
