### ISSUE TITLE
字型問題

### ISSUE THREAD

**Issue by henry-hsieh** [ettoolong/BBSFox-E10S#48]
運作在Win7 64-bit的Firefox 64-bit 55.0.3版 (有開E10S)

- 選擇字型時，點旁邊的箭頭不會有下拉式選單跑出來

- 手動輸入字型名稱有些會無效，不過另外用軟體把字型重新命名後就沒問題

1. 微軟正黑體   (正確)

![default](https://user-images.githubusercontent.com/22725367/30337435-dce3440a-981a-11e7-991a-10102e423b64.png)

2. Microsoft JhengHei   (正確)

![microsoft jhenghei](https://user-images.githubusercontent.com/22725367/30337542-2ffd2836-981b-11e7-8b38-277fab100991.png)

3. 華康細黑體   (正確)

![default](https://user-images.githubusercontent.com/22725367/30337561-40a639f2-981b-11e7-84fd-872e0e9c984d.png)

4. DFHeiLight-B5   (正確)

![dfheilight-b5](https://user-images.githubusercontent.com/22725367/30337595-546ee27c-981b-11e7-823e-75abd98c0be1.png)

5. 華康細黑體(P)   (失效)

會維持上一個字型的模樣

6. 華康仿宋體W6   (錯誤)

![w6](https://user-images.githubusercontent.com/22725367/30337749-e2d33090-981b-11e7-875c-3e2f805cab9a.png)

7. DFFangSongW6-B5   (錯誤)

![dffangsongw6-b5](https://user-images.githubusercontent.com/22725367/30337801-10ad730e-981c-11e7-9046-06fc5353e073.png)

8. DFFangSong   (重新命名過，正確)

![dffangsong](https://user-images.githubusercontent.com/22725367/30337817-1d25ba06-981c-11e7-8ed8-f730c26037b4.png)

9. 華康仿宋體Test   (重新命名過，猜測與名稱中英混和無關，正確)

![test](https://user-images.githubusercontent.com/22725367/30337988-a7087b8c-981c-11e7-8b2c-51343bd9ca32.png)

**Comment by ettoolong** [comment]
因為 FX55 改了一些東西, 造成選字型的下拉選單壞了, 已於 5.0.24 修正.
